/*
const products = [
    {
        key: "1",
        nombre:"Cuchillo Carnicero",
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 3500,
        stock: 10,
        filtro: 2,
        imagen:"assets/Cuchillo Carnicero.jpg",
    },
    {   
        key: "2",
        nombre:"Cuchillo Ciervo",
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 7000, 
        stock: 8, 
        filtro: 2,
        imagen:"assets/Cuchillo mango de ciervo.jpg",
    },
    {
        key: "3", 
        nombre:"Disco Arado c/Tapa",
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 6500, 
        stock: 5, 
        filtro: 1,
        imagen:"assets/Disco para cocinar.jpg",
    },
    {
        key: "4", 
        nombre:"Juego de Palitas", 
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 2500, 
        stock: 20, 
        filtro: 1,
        imagen:"assets/Palita y desparramador.jpg",
    },
    {
        key: "5", 
        nombre:"Juego de Asador",
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.", 
        precio: 3000, 
        stock: 30, 
        filtro: 1,
        imagen:"assets/Juego de asado.jpg",
    },
    {
        key: "6", 
        nombre:"Estaca reforzada",
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.", 
        precio: 6700, 
        stock: 15, 
        filtro: 1,
        imagen:"assets/Estaca para asado.jpg",
    },
    {
        key: "7", 
        nombre:"Guantes Ignifugos",
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.", 
        precio: 3900, 
        stock: 9, 
        filtro: 3,
        imagen:"assets/Guantes ignifugos.jpg",
    },
    {
        key: "8", 
        nombre:"Delantal de Jean", 
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 1500, 
        stock: 20, 
        filtro: 3,
        imagen:"assets/Delantal cocinero.webp",
    },
    {
        key: "9", 
        nombre:"Brasero de hierro", 
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 2000, 
        stock: 15, 
        filtro: 1,
        imagen:"assets/Brasero.jpg",
    },
    {
        key: "10", 
        nombre:"Parrilla movil negra", 
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 18000, 
        stock: 10, 
        filtro: 1,
        imagen:"assets/Parrilla movil.jpg",
    },
    {
        key: "11", 
        nombre:"Asador movil full", 
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 70000, 
        stock: 5, 
        filtro: 1,
        imagen:"assets/Asador redondo.jpg",
    },
    {
        key: "12", 
        nombre:"Espada Galetto", 
        descripcion:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, iure voluptatem laborum beatae, provident in possimus maxime quia, facere delectus esse asperiores natus excepturi? Ipsum, nostrum? Omnis inventore quaerat unde.",
        precio: 800, 
        stock: 50, 
        filtro: 1,
        imagen:"assets/Espadas Galeto.jpg",
    }
]; 

export default products;
*/
